name: zxplayer
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:

  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Initialization environment
          env:
            DEBIAN_FRONTEND: noninteractive
          run: |
            sudo apt-get update
            sudo apt-get -y install unzip curl wget 
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get update
            sudo apt-get install -y nodejs
            node --version
            npm install --global yarn
            node -v
    # steps:
    #   - name: Clone source code
    #     run: |
    #       pwd
    #       git clone --depth=1 https://github.com/hjdhnx/ZyPlayer.git 
    #       cp -R ZyPlayer/* ./

    #       ls -all          
    #       # rm -rf .git
    #       rm -rf .github
    #       ls -all
    #       git config --global user.email 2486251172@qq.com
    #       git config --global user.name hbyhzx
    #       git init
    #       git add .
    #       git commit -m "APP"
    #   - name: Push changes
    #     uses: ad-m/github-push-action@master
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       branch: ${{ github.ref }}
    #   #     # yarn add electron-vite -D
    #   #     # yarn build:linux
    #   #     # cp ./dist/*.AppImage ../
    #   #     # cd ../
    #   #     # rm -rf ZyPlayer/
    #   #     pwd
    #   # - name: Check out Git repository
    #   #   uses: actions/checkout@v4
    #   #   with:
    #   #     submodules: "recursive"
    #   # - name: Install Node.js 18.x
    #   #   uses: actions/setup-node@v4
    #   #   with:
    #   #     node-version: 18.18.0
    #   #     cache: 'yarn'
    #   # - name: Clone source code
    #   #   run: |
    #   #     pwd
    #   #     git clone --depth=1 https://github.com/hjdhnx/ZyPlayer.git 
    #   #     ls
    #   #     yarn add electron-vite -D
    #   #     yarn build:linux
    #   #     cp ./dist/*.AppImage ../
    #   #     cd ../
    #   #     rm -rf ZyPlayer/
    #   # - name: Upload packages
    #   #   uses: actions/upload-artifact@master
    #   #   if: always()
    #   #   with:
    #   #     name: zyplayer-linux-appimage
    #   #     path: /home/runner/work/adai100.github.io/adai100.github.io/ZyPlayer/dist
   
    #   # - name: Upload Firmware to Github Release
    #   #   uses: svenstaro/upload-release-action@v2
    #   #   with:
    #   #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #   #     file: /home/runner/work/adai100.github.io/adai100.github.io/ZyPlayer/dist/*.AppImage*
    #   #     tag: ${{ github.ref }}
    #   #     overwrite: true
    #   #     file_glob: true
